### PR TITLE
Better labels and sizing of graphs

### LINKED ISSUE #73: lca calculations_lca scores
when choosing many lcia methods (in my case 14), the display of the lca scores in the 'lca results' tab is not practical as it's impossible to read the overlapping numbers. a scroll bar would be handy!

### PR DESCRIPTION
**Pull request by cardosan**
textwrap labels and legends, dynamically resize graphs and make sure legends are not cut off.
This fixes  #73,  #74 and #116 (which will not be necessary then)

P.S: combined all my previous changes in this unique commit

### CODE REVIEW

**Comment by haasad** [comment]
Thanks for creating the PR again @cardosan. I checked it and it looks great to me.

**Comment by bsteubing** [comment]
@cardosan and @haasad Thanks to you two for working on this. All these little improvements are really important for the user experience. 
Just a quick feedback: I am looking at it on my laptop at the moment, where the screen is rather small. Here, the legend is still cut off and the text part to the left (activity name) could still be optimized (it is taking up most of the space...). Maybe something for the next overhaul of this part... :-)

**Comment by cardosan** [comment]
HI @bsteubing,
I had played a bit checking different settings but IMO it is hardly possible to always display everything using half of the screen.....or better, maybe possible with a few FU and/or IA but not with many so tried to find a compromise that allows to show everything with a decent font size.

For the legend cutoff (assuming you mean [this legend](https://github.com/LCA-ActivityBrowser/activity-browser/pull/116#issue-175841723)) I tried to make sure that all the labels are displayed. With many labels some were placed outside the canvas (above and below). I preferred to make sure all were displayed and, if necessary, in more than 1 column. I thought was better to increase the size of the left pane than loosing or have very small labels. Guess also for these labels can be easily used [`wrap_text`](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/app/bwutils/commontasks.py#L10).

Regarding the activity names this can be easily changed setting a lower `max_lenght`[format_activity_label](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/app/bwutils/commontasks.py#L22).....I also think should be shortened and by doing so also the legend would be improved

**Comment by bsteubing** [comment]
Hi @cardosan - thanks for your thoughts and effort again! You also raise an issue that is related to the overall UI design, which is whether it makes sense to have two equally sized panels by default. This is linked to #85.

**Comment by cardosan** [comment]
no need to thank ;)
I am using AB and find it very useful. Just trying to return some of the benefits I get sharing my user experience and contributing when I have time.

**Pull request merged**
