### PR TITLE
add process parameters in activity tab

### PR DESCRIPTION
**Pull request by cardosan**
add process parameters as by https://github.com/LCA-ActivityBrowser/activity-browser/issues/7#issuecomment-348275011
in terms of performance navigation seems not to be affected, but obviously fell free not to accept the request if not useful

### CODE REVIEW

**Comment by haasad** [comment]
Cool, thanks Guiseppe, this looks good to me! @bsteubing, you mentioned [here](https://github.com/LCA-ActivityBrowser/activity-browser/issues/7#issuecomment-348431818) that you are worried about the use of the available space. I suggest we merge this and we can add an option to the settings if process parameters should be displayed. What do you think?

**Comment by cardosan** [comment]
Thanks Hadrian. 
BTW, So far the formula is not editable, I can change it before you merge if you wish.

**Comment by haasad** [comment]
I think it's fine if the formula is not editable atm. We will need to rework the editing anyway, see [discussion here](https://github.com/LCA-ActivityBrowser/activity-browser/issues/85#issuecomment-353566842).

**Comment by bsteubing** [comment]
nice and fine with me! Two thoughts to this:
1) in future we might want to add a context menu on the table headers, where you can select what to view and what to hide (and to remember this somewhere)
2) we kicked off several student projects have started yesterday and @AnjeKnottnerus and @TMillross will be working on improving the process editing/modeling, including a dedicated Editor tab or something similar, where at one point also parameters could be entered (looking forward to their work!)

**Comment by cardosan** [comment]
I would suggest to think also about including project and database parameters (best maybe in a separate tab), which are [now handled in bw2](https://docs.brightwaylca.org/intro.html#parameterized-datasets).

**Pull request merged**
