### PR TITLE
version bump 2.2.2

### PR DESCRIPTION
**Pull request by haasad**
Is it ok for you if I release a new version? We still need to come up with some method to plan releases and how to document the changes between versions, see #40. But in the meantime I think we should release a version with all the changes and bugfixes we have added in the last three weeks. Otherwise people that don't install the dev-version from conda get a version that is already kind of outdated.

### CODE REVIEW

**Comment by bsteubing** [comment]
In principle ok, but I have a branch where I revised the tables, which is 90% finished... I think if we get this in, then we definitely have a new version... so what about a (just-before) "Christmas-release"?

**Comment by haasad** [comment]
Cool, that's fine for me.

**Comment by haasad** [comment]
I have fixed the remaining issues that were labeled as `bug`, see #70 and #42. I also added a very minor change to this PR, because your changes to the signals messed with the behaviour of the `DefaultBiosphereDialog`. After this, I think we are really ready for a new release. If you agree @bsteubing , I'll add the 2.2.2 tag and put the new version on conda.

**Comment by bsteubing** [comment]
Great - I agree!

Am 19. Dezember 2017 17:10:20 MEZ schrieb haasad <notifications@github.com>:
>I have fixed the remaining issues that were labeled as `bug`, see #70
>and #42. I also added a very minor change to this PR, because your
>changes to the signals messed with the behaviour of the
>`DefaultBiosphereDialog`. After this, I think we are really ready for a
>new release. If you agree @bsteubing , I'll add the 2.2.2 tag and put
>the new version on conda.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/LCA-ActivityBrowser/activity-browser/pull/72#issuecomment-352805397

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Pull request merged**
