### PR TITLE
Fix negative contributions grouping under Rest issue

### LINKED ISSUE #739: Negative values in contribution analysis aggregated under Rest
In case of absolute the values are aggregated under rest:
image

In case of relative, the contribution of the same negative is shown as positive:
image

### PR DESCRIPTION
**Pull request by nabilahmed739**
Fixes the way bw2-analyzer treats negative contributions on the AB side: https://github.com/brightway-lca/brightway2-analyzer/issues/18
Note: If the above issue is fixed in bw2-analyzer in accordance with the current fix then this change can be reverted after consideration if even the changes in normalize method in multilca class is not required any more.

fixes #739

### CODE REVIEW

**Comment by marc-vdm** [comment]
Would it be a good idea to add TODOs to places that need to be changed back if this gets changed on the BW side?
Otherwise, looks great!

**Comment by cmutel** [comment]
@nabilahmed739 I think it is awesome that you have submitted the PR. Thanks!

I have merged your PR against bw2-analyzer, I think this is a better way to fix the underlying problem. I will release a new version today or tomorrow.

**Comment by nabilahmed739** [comment]
@cmutel Yes, the change in bw2-analyzer would be perfect! 
Could you please let us know the new release version of bw2-analyzer which will be compatible with AB? (Please note that AB has not migrated to bw2.5 yet)

**Comment by nabilahmed739** [comment]
The complete fix for #739 is the combination of bw2-analyzer update to version 0.11.2 and completion of this PR

**Comment by marc-vdm** [comment]
@cmutel I see [bw2analyzer](https://anaconda.org/cmutel/bw2analyzer) was updated, can we finalize this PR on AB side?

**Comment by cmutel** [comment]
@nabilahmed739 @marc-vdm All `bw2analyzer` releases are 2 & 2.5 compatible (or at least they should be!). +1 on merging from me.

**Pull request merged**
