### PR TITLE
Report issues to github directly from activity browser

### PR DESCRIPTION
**Pull request by haasad**
- :beetle: button removed from toolbar
- option to raise issue on github from menubar
- option to raise issue from app in menubar
- some obfuscation for the github auth
- api-access only allows access to other public repos, therefore risk acceptable imo

Further TODOs after this:
- toolbar needs a new layout, eg. where to place debug window button?
- link in Report new bug window is not clickable

### CODE REVIEW

**Comment by haasad** [comment]
Could you maybe try if the report bug from app feature works on your end? I think it's fine now, but just to be sure.

**Comment by bsteubing** [comment]
made two test bug reports... can you see them?

**Comment by bsteubing** [comment]
also the link was still not working... did you push?

**Comment by haasad** [comment]
Issues are working fine. 

The stupid link is somehow a bit more complicated, will look into this at a later time. Problem is that the label of the QInputDialog either isn't rich text or doesn't allow external links to be opened. Maybe need to subclass QInputDialog to make it work.

**Pull request merged**
