### PR TITLE
Run tests for python 3.10

### PR DESCRIPTION
**Pull request by haasad**

### CODE REVIEW

**Comment by marc-vdm** [comment]
@haasad, the logs of the tests have been deleted so I can't check this (or re-run the tests?). 
Do you recall the reason why AB didn't work with `3.10` and what we should do to fix it?

**Comment by haasad** [comment]
I've added a commit to trigger the pipeline again. IIRC there were some segfaults on linux. I'm on holidays currently, won't be at a computer until next week

**Comment by marc-vdm** [comment]
Thanks! Enjoy your holidays!

**Comment by marc-vdm** [comment]
Note, when moving to newer version, we should update the pint fix (#982)

**Comment by marc-vdm** [comment]
@haasad can I close this and #1124 or would you still like to try and figure out what the issue was?

**Comment by haasad** [comment]
Fine to close, can always reopen if needed

**Pull request closed without merging**
