### PR TITLE
Add simple import/export database tool

### PR DESCRIPTION
**Pull request by dgdekoning**

### CODE REVIEW

**Comment by bsteubing** [comment]
Daniel, can you add a try/except statement to catch importing errors? E.g. I can make a new project which doesn't contain the links of the new database, so in that case it should tell me that it cannot properly import the database.

**Comment by bsteubing** [comment]
Also, why not integrate the local/remote imports? Also the remove option currently allows for local imports... perhaps move the local import to the general import wizard and make an export wizard, which for now can just do local exports...

**Comment by dgdekoning** [comment]
Very good reasons, halfway through the suggested changes now, will have a new PR soonish.

**Comment by dgdekoning** [comment]
Closing this in favour of #323

**Pull request closed without merging**
