### PR TITLE
Start tab

### PR DESCRIPTION
**Pull request by haasad**
Small improvements to welcome tab:
- CSS to fit image to available space
- Remove welcome tab after it loses focus to increase available space for other tabs

### CODE REVIEW

**Comment by haasad** [comment]
@bsteubing: I assumed you'd be OK with these changes, we discussed this via Email. Otherwise let me know!

**Comment by bsteubing** [comment]
Great - ok with this!
BTW: why not include a /scripts folder in the /web directory, where we can put the latest versions of d3.js etc. This would also allow offline Sankeys and other visualizations and would be faster. I have already done that locally, if you want me to commit it, just let me know.

**Comment by haasad** [comment]
I think this would be a good idea, however I am unsure about two things (that's why I haven't done it yet):
- Just putting the files in a folder in our repo violates the licenses of the respective projects (ie. already the case for the d3-sankey-diagram lib at the moment)
- I'm not sure if it's necessary, but by loading d3 from http://d3js.org/d3.v3.min.js we always have an up-to-date version

**Comment by bsteubing** [comment]
OK, I see - I haven't thought about this from a license perspective. But I also see plenty of D3 examples not linking to D3 but other repositories. The updated version is a plus, but comes also with the problem of our code breaking if it is not compatible anymore :-)

**Pull request merged**
