### PR TITLE
Lcopt prototype

### PR DESCRIPTION
**Pull request by haasad**
This PR is just for discussion, shouldn't be merged yet in this form. This is a prototype of lcopt running in/with the AB.

You need to have a valid `LCOPT_Setup` project, that you get by running `lcopt-bw2-setup`. You also need a conda env where both the AB and lcopt are installed.

### CODE REVIEW

**Comment by pjamesjoyce** [comment]
Hi guys, this looks really exciting, but I can't get it to work...

I'm getting an error when I try to create a project or load up the example. It seems to be related to `QTextCursor` but with my lack of PyQT knowledge I can't parse it:

```
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
ValueError: I/O operation on uninitialized object
```
Running on windows 7

This is the only place I can find a reference to `QTextCursor`:

https://github.com/LCA-ActivityBrowser/activity-browser/blob/fb77b6a09735669d4111233513b2f05074b1618a/activity_browser/app/ui/utils.py#L21-L28

**Comment by pjamesjoyce** [comment]
lcopt isn't working in the new env I created to test this - checking why now

**Comment by pjamesjoyce** [comment]
Right... it's a problem with flask - I'll have to pin lcopt to version 0.12.2 until I figure out why it doesn't work with v1.0.2

On the bright side, I can now see it working - it looks great! Well done @haasad! 

A couple of minor points:

* it took me a while to figure out I had to go to Windows>Main Window to get back to the activity browser proper from the lcopt window after I'd quit lcopt - a switching button might be cool if it's possible
* Changes made in lcopt don't show up in the activity browser until you navigate away from the database, and navigate back - I guess this is because this is the first use case where the data will be changed by something that isn't the AB itself - a refresh button might be useful

All in all great job though - this is very cool

**Comment by haasad** [comment]
@pjamesjoyce, i added a button to go back to the main menu and the signals to update the ui when lcopt is closed

**Comment by bsteubing** [comment]
Hi, I get a 

> ModuleNotFoundError:  No module named 'lcopt.settings_gui'

Perhaps you still need to commit that file?

**Comment by pjamesjoyce** [comment]
>ModuleNotFoundError: No module named 'lcopt.settings_gui'

That's an lcopt file - try updating lcopt to the latest version of lcopt-dev

**Comment by bsteubing** [comment]
> That's an lcopt file - try updating lcopt to the latest version of lcopt-dev

OK, I see. Now it works. Here my quick feedback:

- I tried the "Load example" button. It works, but takes a long time (as it needs to install the databases in the background) and the user just gets a "frozen" AB in the meantime... this could still be improved (@haasad don't know if a separate thread could help here). 
- with the upcoming new version of the AB, the general layout has shifted (basically the panels are flipped, e.g. the project tab is now on the left, and the right panel occupies roughly 3/4 of the horizontal space). Within the new layout, I would suggest to open a tab in the right panel for LCOPT instead of a whole stacked window; this way all the other AB functionality is more accessible

**Comment by bsteubing** [comment]
@haasad : if you want to merge, please go ahead (I'll try to remember the last bullet point (panel) when I integrate all the changes for the upcoming new version)

**Comment by pjamesjoyce** [comment]
@haasad maybe hold off until I've sorted this issue - pjamesjoyce/lcopt#49
The new single project implementation still has a couple of bugs that need to be worked out

**Comment by bsteubing** [comment]
Just a quick update on the timing for the next release (as I see it, perhaps @haasad you also have thoughts to this): there is a lot in the AB-pipeline, which will give a great next version of the AB. However, some of the new features are not quite ready and I am pretty busy in September, so I think a realistic time horizon for the next release is somewhere around mid October.

**Comment by haasad** [comment]
I agree with @pjamesjoyce, this branch still needs some work before we can merge it. Still have some work in progress that I haven't commited yet. Will try to find the time in the next days/weeks

**Comment by bsteubing** [comment]
OK. Let's coordinate this at some point in October, to see how all the new features in the AB (e.g. lcopt, new data entry by tmillross, new results analysis tabs, graph explorer and sankey) play together.

**Comment by pjamesjoyce** [comment]
pjamesjoyce/lcopt#49 is now fixed

**Pull request closed without merging**
