### PR TITLE
Fix for #521 + cleanup + tooltips

### PR DESCRIPTION
**Pull request by marc-vdm**
Fix for #521 and some additional cleanup and tooltips

### CODE REVIEW

**Comment by dgdekoning** [comment]
I've looked over the changes and they mostly look good. I've found two places where we can make the code cleaner and easier to understand.

**Comment by dgdekoning** [comment]
https://github.com/LCA-ActivityBrowser/activity-browser/blob/00f33b01b82de8bb3ef0334700ed188dd28db758/activity_browser/layouts/tabs/project_manager.py#L161-L175

the `update_widget` code for the `DatabaseWidget` can be made cleaner as follows:

```python
    def update_widget(self):
        no_databases = self.table.rowCount() == 0
        self.add_default_data_button.setVisible(no_databases)
        self.import_database_button.setVisible(not no_databases)
        self.new_database_button.setVisible(not no_databases)
        self.label_no_database_selected.setVisible(not no_databases)
        self.table.setVisible(not no_databases)
        self.label_change_readonly.setVisible(not no_databases)
```

**Comment by dgdekoning** [comment]
In addition to the above, we can then simplify https://github.com/LCA-ActivityBrowser/activity-browser/blob/00f33b01b82de8bb3ef0334700ed188dd28db758/activity_browser/layouts/tabs/project_manager.py#L50-L54
into
```python
self.activity_biosphere_widget.setVisible(not no_databases)
```

**Comment by marc-vdm** [comment]
@dgdekoning Suggestions are now included, with one minor change:
`self.label_no_database_selected.setVisible(not no_databases)` had to be moved to the part of your second comment to work.

**Comment by dgdekoning** [comment]
> @dgdekoning Suggestions are now included, with one minor change:
> `self.label_no_database_selected.setVisible(not no_databases)` had to be moved to the part of your second comment to work.

This does mean we get situations like this:
image
We want to hide the 'select a database' label when there are no databases to select.

**Pull request merged**
