### PR TITLE
Adding error message if no scenario file is loaded in a scenario LCA

### PR DESCRIPTION
**Pull request by bsteubing**
## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation, please follow the [numpy style guide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] Update tests.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `feature`, `ui`, `change`, `documentation`, `breaking`, `ci`
      as they show up in the changelog
- [ ] Link this PR to related issues.

### CODE REVIEW

**Comment by bsteubing** [comment]
@marc-vdm any clue why the python 3.8 tests are failing? Does this have to do with the assert statement that I added???

**Comment by marc-vdm** [comment]
> @marc-vdm any clue why the python 3.8 tests are failing? Does this have to do with the assert statement that I added???

I don't think so, The update from Jon you merged last is failing with the same error. I think it's just a dependency problem. We're planning to move away from `3.8` anyway, so I think it'd be good for now to just require only `3.9` and once we're ready, move to `3.11` | `3.12`.


With regards to your code haven't tested it but if the assertion fails, this will only be printed to the terminal correct? I think we should give this as a popup instead?

**Comment by marc-vdm** [comment]
@bsteubing The testing problem is resolved.

Could you still look at the this question?
> If the assertion fails, this will only be printed to the terminal correct? I think we should give this as a popup instead?

**Comment by bsteubing** [comment]
It should give a pop-up already. Interesting that the testing problem is resolved now, so it is good to merge.

**Pull request merged**
