### PR TITLE
Allow deleting of processes/activities with downstream consumers

### PR DESCRIPTION
**Pull request by marc-vdm**
(fix for #720)

### CODE REVIEW

**Comment by bsteubing** [comment]
Hi @marc-vdm I think this is not yet the general solution... for example, an activity can have _several_ self-references:
image

Could you also test what happens in brightway if you try to delete such an activity? Maybe instead of catching it ourselves if an activity can be deleted or not, we should better rely on brightway and do a try-except statement catching the specific brightway error.
I copy here also @cmutel

**Comment by marc-vdm** [comment]
>an activity can have several self-references

Do we even want this? What is the practical use of having multiple of the same input exchanges?

>Maybe instead of catching it ourselves if an activity can be deleted or not, we should better rely on brightway

Fair enough. I noticed we had a check in our code, so I assumed BW doesn't check for problems like this. This could indeed be useful too.

**Comment by cmutel** [comment]
> Do we even want this? What is the practical use of having multiple of the same input exchanges?
I also mean this question in general, when does it make sense to have multiple of the same exchange as inputs, even if they wouldn't be from the same activity?

We do want this:

1. In general we want to support different modelling paradigms
2. It is already used in common databases such as ecoinvent
3. It makes sense, e.g. you want to separately model two transport steps, both with the same vehicle type but with different distances or loading factors, or separate uncertainty

**Comment by marc-vdm** [comment]
@cmutel 
Alright that's clear. I see you've made an issue for this on BW. What is your plan? Do you think we should use your exceptions in AB to handle this or should I write a solution on AB side independent of yours?

Either way, this will add to computation time for processes with many exchanges, as we'd need to check for each exchange whether it is a reference to self, where the original solution only checked `if len(exchanges)==1`.

**Comment by bsteubing** [comment]
Since bw seems to remove exchanges from downstream processes to the process to be deleted, we could also just stick with brighway and prompt the user like this: "The process you are about to delete seems to be used by other processes [provide a list here]. By deleting this process, the input to the above processes will be removed as well. Do you want this?"

What do you think @cmutel and @marc-vdm ?

**Comment by marc-vdm** [comment]
This sort-of already happens, but right now, the user has no option to actually continue (see current popup below). 

We could just add the option to continue to that dialog. Do we want an entire table with downstream consumers (which could be many) Or should we refer users to the `Downstream Consumers` table to review?
image

**Comment by marc-vdm** [comment]
I've removed the check if downstream consumers are self and updated the dialog to the following:
image

@cmutel @bsteubing  Do you think this is sufficient?

**Comment by cmutel** [comment]
@marc-vdm I closed the [bw2-data issue](https://github.com/brightway-lca/brightway2-data/issues/94) by adding a test, but the deletion of multiple "self" exchanges already worked.

The proposed dialog seems fine with me. It shouldn't take any noticable time to iterate over even a few hundred exchanges, I routinely iterate over whole databases.

**Comment by marc-vdm** [comment]
@cmutel Thanks! Already discussed with @bsteubing. I've updated the wording (as 'downstream consumers' are not always 'consumers' e.g. in case of waste treatment), but I'll merge now.

**Pull request merged**
