### PR TITLE
Version 2.3.2

### PR DESCRIPTION
**Pull request by dgdekoning**

### CODE REVIEW

**Comment by bsteubing** [comment]
Congratulations Daniel!!

**Comment by ntropy-esa** [comment]
Nice feature! Greatly needed!

**Comment by dgdekoning** [comment]
Thanks :)

**Comment by ntropy-esa** [comment]
Question: 
What is needed for this aggregation feature to also 'aggregate by user-defined tags' as it is possible with bw2analyzer.traverse_tagged_databases (https://docs.brightwaylca.org/technical/bw2analyzer.html#supply-chain-traversal) ?

**Comment by dgdekoning** [comment]
Thanks for making me aware of that :D

The current aggregation feature makes heavy use of the pandas dataframe in the MetaDataStore class to quickly aggregate the results of multiple LCA calculations (X functional units * Y impact categories) at once . So it kind of sidesteps the solution presented by bw2analyser.

Thinking out loud the features needed for aggregating by user defined tags would be something like this:

- Allowing the user to set tags within the activity browser (possibly by expanding the activity viewer tab?).
- Expanding the existing `LCA Results` or `Inventory` tab to allow selection of a specific functional unit & impact method combination. Then drawing the inventory for that combination in a table similar to the `Inventory` tab.
- Reading the user-defined tags from brightway should then allow us to create a dropdown menu that triggers aggregation for the inventory.

Reading this it doesn't actually look like much work but there are probably some gotcha's I'm overlooking. 

As a quick sneak peek: I'm currently in the midst of [adding brightway parameterization to the UI](https://github.com/dgdekoning/activity-browser/tree/add-parameter-tab) and I have plans to add github projects and milestones with these kinds of requests to better keep track of them.

**Pull request merged**
