### PR TITLE
Add brightway parameterization functionality

### PR DESCRIPTION
**Pull request by dgdekoning**
Using what is already present in the brightway2 code, allow users to parameterize their systems.

This pull requests adds a new 'Parameters' tab next to the 'LCA Setup' tab in which users can set project-, database- and activity level parameters. See [here](https://docs.brightwaylca.org/intro.html#parameterized-datasets) for an extended explanation of the parameter system in brightway.
Error messages are shown where possible and allow for different choices (roll-back incorrect new parameters or do nothing and allow the user to save again after editing).
Warning messages are given if the user attempts to set parameters on activities from read-only databases or on activities which are not of type 'process'.

The created and saved parameters are immediately usable by the system when performing the default LCA calculations.

TODO:
- [x] Add '?' icons with hover explanation text (quick and simple 'what do' for each location). 
- [x] Add signal to delete/close any LCA result tabs when a new parameter of any type is created.
- [x] Add 'order' field for activity parameters to allow complete `bw.parameters` functionality.
- [x] Add tests for the new tabs and tables.
- [x] Allow exchange parameters to be removed in the same way as activity parameters can be.
  - Wiring for this is already in place, just needs tiny amount of work.
- [x] ~~Allow project and database parameters to be removed by the user.~~ Nope, read the code wrong, project and database parameters cannot be removed through the `ParameterManager`.
  - ~~Not supported by brightway, and for good reason: Removing these parameters blindly can and will mess with downstream parameters using the removed parameter.~~
  - ~~Is possible by removing the rows from the dataframe and then calling 'save parameters', brightway will handle the rest.~~

### CODE REVIEW

**Comment by dgdekoning** [comment]
Brilliant, just found out I have been building classes allllll wrong.

**Comment by dgdekoning** [comment]
> Brilliant, just found out I have been building classes allllll wrong.

Or rather, I thought I was, but it might just be pytest-qt gaslighting me.

**Comment by dgdekoning** [comment]
So yeah, for some reason I cannot get the qtbot.mouseClick to work in my new tests on windows. Going to try and run them on linux as well and see if that yields the same results.

**Comment by dgdekoning** [comment]
@cmutel, @bsteubing: How does this look?

**Comment by dgdekoning** [comment]
I've thought of two more things to add:

- [ ] A list on the right side of the space of the 'exchanges' parameter tab containing the project and database parameter names (so they can easily be used in the formulas of the activities and exchanges).
- [ ] Signal and hook for unsetting the formulas of exchanges when the related activity parameter is removed (similar to how the exchange table is updated when an activity parameter is removed).

**Comment by cmutel** [comment]
I won't be able to look at this in detail until after I get back and catch up, i.e. mid-August. Remind me if it seems like I have forgotten, or just merge - you know what you are doing :)

**Comment by dgdekoning** [comment]
Thanks! I've been working on adding `uncertainty` fields to all of the parameters (which is why I was suddenly messing with stats_arrays), as well as improving the separation between the `model` and `view` classes.

A lot of the more generic model/view/delegate code introduced here can be used to refactor almost all of the other other table classes inheriting from QTableWidget  so I'm going to wait till bernhard gets back and discuss it with him. Plenty more things to work on in the mean time :)

**Comment by dgdekoning** [comment]
At the request of @bsteubing I will be splitting this pull request into multiple different ones:

1. Introduces the changes for model/view/delegate.
2. Introduces the code for immediately generating QIcon objects from loaded icons.
3. Dependent on the **1**, introduces the Parameter tables, related code for tabs and tests.

This will allow for some more work to be done on the UI-side of handling parameters, as the current setup is not quite clear as to how everything works.

**Comment by dgdekoning** [comment]
Closing in favour of #260.

**Pull request closed without merging**
