### PR TITLE
Plugins manager

### PR DESCRIPTION
**Pull request by Pan6ora**
Add functionalities to Activity Browser using plugins.

This feature was implemented trying to add as few code as possible.
For documentation about this feature you can refer to the [fork README](https://github.com/Pan6ora/activity-browser). More documentation on how to create a plugin can also be found in the [plugin template repos](https://github.com/Pan6ora/activity-browser-plugin-template).

As discussed with @bsteubing, @marc-vdm and @Zoophobus the plugins code management is made at AB global scope, but plugins are chosen per-project.

For any question on this feature, contact me or open an issue in [my fork repository](https://github.com/Pan6ora/activity-browser).

## Main characteristics

- A plugin is a 7z archive containing a Python library
- A plugin can add any content in two tabs (Left/Right)
- Plugins connect to AB through signals
- Plugins code is stored at AB global scope
- Plugins can be selected by project

### bug

- check if all plugins in AB_project_settings.json exist when loading project
- add tests for the plugin manager
- add a compatibility checkup with AB version

### feature

- add an `info` button to plugins linked to some documentation
- add ability for a plugin to modify menus and wizards
- let plugins add additional libraries

### CODE REVIEW

**Comment by marc-vdm** [comment]
This is really awesome @Pan6ora! Thanks a lot for contributing this awesome feature. I'll try and play with it a little when I have time.

One question/feature request: Would it be possible to install additional libraries (like if `pandas` was not used by AB by default) through installing a plugin, or would the provider of a package need to provide additional libraries themselves (just copy pasting external libraries) when publishing their plugin?

**Comment by Pan6ora** [comment]
> This is really awesome @Pan6ora! Thanks a lot for contributing this awesome feature. I'll try and play with it a little when I have time.
> 
> One question/feature request: Would it be possible to install additional libraries (like if `pandas` was not used by AB by default) through installing a plugin, or would the provider of a package need to provide additional libraries themselves (just copy pasting external libraries) when publishing their plugin?

Well pointed out ! This is a question I asked myself some times ago but then I forgot to work on it. This is for sure a necessary feature. I need to find out the best way to implement it (hopefully a "Pythonic" way). If you have a preference for some workflow don't hesitate to share your thoughts.

**Comment by Zoophobus** [comment]
Hi Pan6ora, thanks that's fantastic to see. It looks great, just weird with the tests that the catchsegv is failing in the Ubuntu environments. I'll have a look at the catchsegv but will merge this soon as is. Regarding the dependencies, while I haven't tested this would it not be possible to simply use a .yml file for the plugins to install these in the ab environment? The only other thing I can think of is whether we should try and develop a bit of documentation surrounding this too?

**Comment by Pan6ora** [comment]
> just weird with the tests that the catchsegv is failing in the Ubuntu environments. 

Yes that's strange, I have the same problem on my own repos. I'll try to investigate this one too.

> Regarding the dependencies, while I haven't tested this would it not be possible to simply use a .yml file for the plugins to install these in the ab environment? 

Sounds good to me. I will try something like this as soon as possible. 

> The only other thing I can think of is whether we should try and develop a bit of documentation surrounding this too?

There is already some documentation in the README of both my fork and the plugin template (as I pointed out in my first message). Where would you like to put it ?

**Comment by Zoophobus** [comment]
aarggh, sorry I seem to have made some problems. `There is already some documentation in the README of both my fork and the plugin template (as I pointed out in my first message). Where would you like to put it ?` Also sorry I didn't read your work well enough I'll have a look at your documentation! Also I guess you will have noticed the arrival of some stupid Qt errors along with this catchsegv, this appears to be no longer included in later versions of libc-bin

**Comment by Pan6ora** [comment]
@Zoophobus  I was able to fix the catchsegv issue on my branch by adding `glibc-tools` to linux dependencies (as you pointed out it has been removed in latest Ubuntu version). An other solution is to switch from `ubuntu-latest` (which is now ubuntu-22.04) to `ubuntu-20.04`.

After solving this, I had another issue with pytest not finding `libQt5WebEngineWidgets`. I did some testing and it seems to me that the problem is with the last update of pyside2 on conda (which was pushed yesterday). Forcing an older version (for example `pyside2 5.15.5` in _ci/recipe/stable/meta.yaml`) solved it.

My conclusion is that both these problems weren't linked to the plugin manager.

**Pull request closed without merging**
